---
name: continuous-integration

on: [push, pull_request]

jobs:

    pre-commit:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
                  cache: pip
                  cache-dependency-path: |
                      .pre-commit-config.yaml
                      **/setup.cfg
                      **/pyproject.toml
                      **/requirements*.txt

            - name: Install dependencies
              run: python -m pip install pre-commit~=2.20

            - name: Run pre-commit
              run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

    #test_generate_json:
    #    runs-on: ubuntu-latest
    #    steps:
    #        - uses: actions/checkout@v3

    #        - name: Set up Python 3.10
    #          uses: actions/setup-python@v4
    #          with:
    #              python-version: '3.10'

    #        - name: Install dependencies
    #          run: |
    #              python -m pip install --upgrade pip
    #              pip install -r ./.make_ghpages/requirements.txt

    #        - name: Collect all setup info of computers/codes into a single JSON file.
    #          run: |-
    #              python "${GITHUB_WORKSPACE}/.make_ghpages/generate_json.py"
